name: Input DropDown Workflow

on:
  workflow_dispatch:
    inputs:
      batch:
        description: 'Select a batch number'
        required: true
        default: '1'
        type: choice
        options:
          - 1
          - 2
          - 3
          - 4

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Print Environment Variables
        shell: pwsh
        run: |
          Get-ChildItem Env:

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          $eventPath = $env:GITHUB_EVENT_PATH
          $eventData = Get-Content $eventPath | ConvertFrom-Json
          $batch = $eventData.inputs.batch
          Write-Host "Selected batch: $batch"
