name: Tag and Release with API

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Run Count
        id: get_run_count
        shell: pwsh
        run: |
          $runCount = $Env:GITHUB_RUN_NUMBER
          $version = "v${runCount}"
          Write-Output "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Get Commit SHA
        id: get_commit_sha
        shell: pwsh
        run: |
          $commitSHA = git rev-parse HEAD
          Write-Output "COMMIT_SHA=$commitSHA" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create Tag via API
        shell: pwsh
        run: |
          $tagName = $Env:VERSION
          $commitSHA = $Env:COMMIT_SHA

          $token = $Env:GITHUB_TOKEN
          $headers = @{
              "Authorization" = "token $token"
              "Accept" = "application/vnd.github.v3+json"
          }

          $body = @{
              ref = "refs/tags/$tagName"
              sha = $commitSHA
          } | ConvertTo-Json

          $uri = "https://api.github.com/repos/gpranaykumar/GH-Action-Tag-Release/git/refs"

          try {
              Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $body -ErrorAction Stop
              Write-Output "Tag $tagName created successfully."
          } catch {
              Write-Error "Error creating tag: $_"
              exit 1
          }

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
