name: Tag and Release

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Git
      #   shell: pwsh
      #   run: |
      #     git config --global user.name 'github-actions'
      #     git config --global user.email 'github-actions@github.com'

      - name: Get Run Count
        id: get_run_count
        shell: pwsh
        run: |
          $runCount = $Env:GITHUB_RUN_NUMBER
          $version = "v${runCount}"
          Write-Output "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create Git Tag
        shell: pwsh
        run: |
          $tag = $Env:VERSION
          git tag $tag
          git push origin $tag

      - name: Create GitHub Release
        shell: pwsh
        run: |
          $tag = $Env:VERSION
          $body = "Automated release for version $tag"

          $token = $Env:GITHUB_TOKEN
          $headers = @{
              "Authorization" = "token $token"
              "Accept" = "application/vnd.github.v3+json"
          }
          $uri = "https://api.github.com/repos/gpranaykumar/GH-Action-Tag-Release/releases"
          $bodyObject = @{
              tag_name = $tag
              name = "Release $tag"
              body = $body
              draft = $false
              prerelease = $false
          } | ConvertTo-Json

          try {
              Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $bodyObject -ErrorAction Stop
          } catch {
              Write-Error $_.Exception.Message
              exit 1
          }

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
