name: Tag and Release

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up Git
      #   run: |
      #     git config --global user.name 'github-actions'
      #     git config --global user.email 'github-actions@github.com'
      #   shell: pwsh

      - name: Get Run Count
        id: get_run_count
        run: |
          $runCount = $Env:GITHUB_RUN_NUMBER
          $version = "v${runCount}"
          echo "::set-output name=VERSION::$version"

      - name: Create Git Tag
        id: create_tag
        run: |
          $tag = $Env:VERSION
          git tag $tag
          git push origin $tag
          echo "::set-output name=TAG::$tag"

      - name: Create GitHub Release
        id: create_release
        run: |
          $tag = $Env:TAG
          $body = "Automated release for version $tag"

          $token = $Env:GITHUB_TOKEN
          $headers = @{
              "Authorization" = "token $token"
              "Accept" = "application/vnd.github.v3+json"
          }
          $uri = "https://api.github.com/repos/owner/repo/releases"
          $bodyObject = @{
              tag_name = $tag
              name = "Release $tag"
              body = $body
              draft = $false
              prerelease = $false
          } | ConvertTo-Json

          Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $bodyObject

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
